// source https://en.wikipedia.org/wiki/List_of_galaxies
/** list of real-world named galaxies */
export const galaxyName = [
  'Andromeda',
  'Antennae',
  'Backward',
  'Black Eye',
  'Butterfly',
  'Cartwheel',
  'Cigar',
  'Circinus',
  'Coma Pinwheel',
  'Comet',
  'Cosmos Redshift 7',
  'Eye of Sauron',
  'Fireworks',
  'Hockey Stick',
  `Hoag's Object`,
  `Lindsay-Shapley Ring`,
  'Little Sombrero',
  'Medusa Merger',
  `Mayall's Object`,
  'Milky Way',
  'Needle',
  'Pinwheel',
  'Sculptor',
  'Sombrero',
  'Southern Pinwheel',
  'Sunflower',
  'Tadpole',
  'Triangulum',
  'Whirlpool',
];
